//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository.Library {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataRepository.Library.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;channel&gt;&lt;title&gt;PSI Update&lt;/title&gt;&lt;source&gt;Airviro&lt;/source&gt;&lt;item&gt;&lt;region&gt;&lt;id&gt;rNO&lt;/id&gt;&lt;latitude&gt;1.41803&lt;/latitude&gt;&lt;longitude&gt;103.82000&lt;/longitude&gt;&lt;record timestamp=&quot;20160426170000&quot;&gt;&lt;reading type=&quot;NPSI&quot; value=&quot;63&quot;/&gt;&lt;reading type=&quot;NPSI_PM25_3HR&quot; value=&quot;75&quot;/&gt;&lt;reading type=&quot;NO2_1HR_MAX&quot; value=&quot;76&quot;/&gt;&lt;reading type=&quot;PM10_24HR&quot; value=&quot;37&quot;/&gt;&lt;reading type=&quot;PM25_24HR&quot; value=&quot;23&quot;/&gt;&lt;reading type=&quot;SO2_24HR&quot; value=&quot;5&quot;/&gt;&lt;reading type=&quot;CO_8HR_MAX&quot; value=&quot;0.41&quot;/&gt;&lt;reading type=&quot;O3_8HR_MAX&quot; value=&quot;50&quot;/&gt;&lt;reading type=&quot;NPSI_CO&quot; va [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string psi {
            get {
                return ResourceManager.GetString("psi", resourceCulture);
            }
        }
    }
}
