//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidSmthApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AndroidSmthApp.ResourceData", typeof(ResourceData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;id&quot;: &quot;1067854&quot;,
        ///        &quot;author_id&quot;: &quot;tabE&quot;,
        ///        &quot;time&quot;: &quot;1464431922&quot;,
        ///        &quot;count&quot;: &quot;256&quot;,
        ///        &quot;board&quot;: &quot;Pregnancy&quot;,
        ///        &quot;subject&quot;: &quot;[求助]晴天霹雳，NT结果，胎儿没有手，人民基本确诊。。。。。&quot;
        ///    },
        ///    {
        ///        &quot;id&quot;: &quot;1270390&quot;,
        ///        &quot;author_id&quot;: &quot;sinlo&quot;,
        ///        &quot;time&quot;: &quot;1464431999&quot;,
        ///        &quot;count&quot;: &quot;137&quot;,
        ///        &quot;board&quot;: &quot;Picture&quot;,
        ///        &quot;subject&quot;: &quot;82年生高中都考不上的人，已经要当市长了&quot;
        ///    },
        ///    {
        ///        &quot;id&quot;: &quot;2653004&quot;,
        ///        &quot;author_id&quot;: &quot;prretyboyz&quot;,
        ///        &quot;time&quot;: &quot;1464431647&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Top10 {
            get {
                return ResourceManager.GetString("Top10", resourceCulture);
            }
        }
    }
}
